name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"

jobs:
  release:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Ship it
        if: ${{ github.event.inputs.tag != '' }} # don't release if no tag is specified
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          draft: false
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.tag }}
          commit: "main"
      - name: Configure AWS credentials
        if: ${{ github.event.inputs.tag != '' }} # don't release if no tag is specified
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: "arn:aws:iam::710015040892:role/ComposeSpecWebsite-20220215151844232500000002"
          role-session-name: deploy-compose-spec-website
          aws-region: us-east-1
      - name: Push website to S3
        run: |
          aws s3 sync ./website s3://compose-spec-site-prod --acl=private
